### ISSUE TITLE
adjusting filtering parameters in ds.filter_cells()

### ISSUE THREAD

**Issue by rwarfvinge** [parashardhapola/scarf#27]
Hi, 

How do I adjust filtering parameters during cell filtering? If I try to change the first given values for "lows" and "highs" the plot axes wont change when re-plotting the cell distributions. I can reset the values if i convert the hf5 file to a datastore object again, but this is quite tedious. Is there a another way around this?

reader = scarf.CrH5Reader(S1, file_type='rna')
writer = scarf.CrToZarr(reader, "S1.zarr", chunk_size=(2000, 5000)) 
writer.dump()

ds = scarf.DataStore("S1.zarr", nthreads=6, default_assay='RNA')
ds.plot_cells_dists()
ds.filter_cells(attrs=['RNA_nFeatures', 'RNA_percentMito'], lows=[**1000, -1**], highs=[**7000, 15**])
ds.plot_cells_dists(cell_key='I', color='coral')

**Comment by parashardhapola** [comment]
Hi,

Thanks for reporting this issue.
The original idea with `filter_cells` was this:
if a user reruns `filter_cells`, then the cells that were filtered out remain filtered out even if they pass the new thresholds.

Obviously, this was a flawed design but I will keep this behavior as default for backward compatibility.

To override this behavior and to have completely fresh filtering you can use the parameter `reset_previous` and set it to `True`.

This parameter is available in version `0.7.4`, so please update Scarf:
`pip install -U scarf-toolkit`

Please close this issue if resolved.

/Parashar

**Comment by rwarfvinge** [comment]
This works perfect, Thanks!
