### ISSUE TITLE
Missing figure legends in PNGs

### ISSUE THREAD

**Issue by rwarfvinge** [parashardhapola/scarf#29]
Hi,

When exporting UMAPs as PNGs with ds.plot_layout() the figure legend is cut off. Possible to fix?

Example code: 
ds.plot_layout(layout_key =  "RNA_UMAP", color_by = "maxHTO", cmap= "Set3", savename=f"{sample}_UMAP.png")   

best,

Rebecca

**Comment by parashardhapola** [comment]
Hi,

Thanks for reporting this.

I have made a quick fix for this.
Can you try installing the development version of Scarf like this:
`pip install git+git://github.com/parashardhapola/scarf.git@master`

If this works, I will include this in the upcoming `0.7.5` release

Parashar

**Comment by rwarfvinge** [comment]
Thanks, but unfortunately I does not seem to work in my hands. I installed the development version, updated scarf in jupyter but legend was still missing in output.

**Comment by rwarfvinge** [comment]
Noticed it now works, thanks for fixing this!
