### ISSUE TITLE
Rename ds.cells.columns?

### ISSUE THREAD

**Issue by rwarfvinge** [parashardhapola/scarf#30]
Is there a function to rename ds.cells.columns?
Tried ds.cells.rename(columns = {A : B}),  couldn't find info in tutorial or API.

**Comment by parashardhapola** [comment]
Hi,

I assume you mean renaming the label of individual columns rather than the values inside the column.

Such a `rename` function is not implemented. If there is a lot of demand for it then I will do so.

For now, this is the workaround:

```
col_data =  ds.cells.fetch_all('A')
ds.cells.drop('A')
ds.cells.insert('B', col_data, overwrite=True)
```

Does that work for you?

**Comment by rwarfvinge** [comment]
Works fine for me, thanks!
