### ISSUE TITLE
retain QC filtering and columns after scarf.make.subset()

### ISSUE THREAD

**Issue by rwarfvinge** [parashardhapola/scarf#32]
Hi, 

In regards to my former issue: "Retain QC filtering after scarf.ZarrMerge()?"
https://github.com/parashardhapola/scarf/issues/28

I realized that I lose the QC filtering already at the make_subset,  the step before ZarrMerge . So a similar fix to retain the QC filtering and columns after scarf.make_subset is also needed. Possible to add?

**Comment by parashardhapola** [comment]
Version 0.7.5 should fix this
Please update scarf: `pip install -U scarf-toolkit`

**Comment by rwarfvinge** [comment]
Perfect, thanks! Works perfect now.
