### ISSUE TITLE
export cluster markers

### ISSUE THREAD

**Issue by sommarin** [parashardhapola/scarf#37]
Hi, 
I'm trying to export cluster markers to a csv file. And thus I tried: "ds.export_markers_to_csv(from_assay='RNA', group_key= 'RNA_leiden_cluster', csv_filename= './tables/cluster_markers/Cluster_markers.csv')". 
And got the error message "AttributeError: module 'scarf' has no attribute 'export_markers_to_csv'".

**Comment by parashardhapola** [comment]
Which version of Scarf are you using?
Check using: `print (scarf.__version__)`

`export_markers_to_csv` is available in 0.7.4 upwards
