### ISSUE TITLE
a problem import scarf (wrong version of tqdm)

### ISSUE THREAD

**Issue by liuweihanty** [parashardhapola/scarf#60]
Dear scarf team, I installed scarf using pip successfully, but I encounter the error message below when I tried to import scarf.
Weirdly I already installed tqdm by pip install tqdm, and it says **Requirement already satisfied: tqdm in ./opt/anaconda3/lib/python3.8/site-packages (4.50.2)**. Do you by any chance know what might cause this error message? Thank you very much!

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b7438635443d> in <module>
      1 import pandas as pd
----> 2 import scarf

~/opt/anaconda3/lib/python3.8/site-packages/scarf/__init__.py in <module>
     45     print("Scarf is not installed", flush=True)
     46 
---> 47 from .datastore import *
     48 from .readers import *
     49 from .writers import *

~/opt/anaconda3/lib/python3.8/site-packages/scarf/datastore.py in <module>
     13 import dask.array as daskarr
     14 from scipy.sparse import csr_matrix, coo_matrix
---> 15 from .writers import create_zarr_dataset, create_zarr_obj_array
     16 from .metadata import MetaData
     17 from .assay import Assay, RNAassay, ATACassay, ADTassay

~/opt/anaconda3/lib/python3.8/site-packages/scarf/writers.py in <module>
     23 from typing import Any, Tuple, List, Union, Dict
     24 import numpy as np
---> 25 from .readers import CrReader, H5adReader, NaboH5Reader, LoomReader
     26 import os
     27 import pandas as pd

~/opt/anaconda3/lib/python3.8/site-packages/scarf/readers.py in <module>
     20 from typing import IO
     21 import h5py
---> 22 from .utils import logger, tqdmbar
     23 
     24 __all__ = [

~/opt/anaconda3/lib/python3.8/site-packages/scarf/utils.py in <module>
     14 import sys
     15 import numpy as np
---> 16 from tqdm.dask import TqdmCallback
     17 from dask.array.core import Array
     18 from tqdm.auto import tqdm as std_tqdm

ModuleNotFoundError: No module named 'tqdm.dask'`

**Comment by razofz** [comment]
I tried reproducing this, but couldn't. What I did:

```bash
conda create -n scarf-issue-tqdm-pip
conda activate scarf-issue-tqdm-pip
conda install pip
pip install tqdm
pip install scarf
python -c 'import scarf'
```

with conda v4.10.1, and scarf was imported.

So it might be an issue with virtual environments and the activation of them, or it might be something with specific versions of packages. Could you please:

- tell me if you are using virtual environments
    - if so, make sure you have the right environment activated (you can check this with e. g. `which python` to see which python interpreter is currently active, it should point to your environment location when the environment is activated)
    - if the right env is activated and the issue persists, export/freeze the the environment so I can see the packages' versions and see if I can reproduce the issue
    
Thank you!

**Comment by parashardhapola** [comment]
Hi @liuweihanty 

This can be an issue if an older version of tqdm is already installed. As @razofz  has suggested, it is always best to start in a new virtual environment or a conda environment.

If you want to fix this in your current base environment then you may try this: (`-U` will update tqdm)
`pip install -U tqdm`

**Comment by parashardhapola** [comment]
I guess this is resolved. Feel free to open again if the issue persists.
