### ISSUE TITLE
If the assay is not RNA - e.g. spliced from a kallisto/bustools run

### ISSUE THREAD

**Issue by stela2502** [parashardhapola/scarf#62]
If I load a loom file from a kallisto/bustools run using
```
reader = scarf.readers.LoomReader( ifile, cell_names_key='CellID', feature_names_key="Gene")
writer = scarf.LoomToZarr(
    reader,
    zarr_fn='scarf_datasets/data/data.zarr',
    chunk_size=(2000, 1000),
    assay_name = "spliced"
)
writer.dump(batch_size=1000)
ds = scarf.DataStore(
    'scarf_datasets/data/data.zarr',
    nthreads=4,
    min_features_per_cell=100
)
```

This step breaks:
```
ds.mark_hvgs(
    min_cells=20,
    top_n=500,
    min_mean=-3,
    max_mean=2,
    max_var=6,
    from_assay='spliced'
)
```
Mark the  from_assay='spliced' - but then I also need this:
```
ds._get_assay('spliced').__class__ = scarf.assay.RNAassay
```
As this assay was a scarf.assay.Assay class when loaded.

**Comment by stela2502** [comment]
As this was all recoverable I now might have found a bug:
```
ds.make_graph(
    feat_key='hvgs',
    k=11,
    dims=15,
    n_centroids=100,
    from_assay='spliced' # same error if I leave that out...
)
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-a0c6cec879df> in <module>
----> 1 ds.make_graph(
      2     feat_key='hvgs',
      3     k=11,
      4     dims=15,
      5     n_centroids=100,

/usr/local/lib/python3.8/dist-packages/scarf/datastore.py in make_graph(self, from_assay, cell_key, feat_key, pca_cell_key, reduction_method, dims, k, ann_metric, ann_efc, ann_ef, ann_m, ann_parallel, rand_state, n_centroids, batch_size, log_transform, renormalize_subset, local_connectivity, bandwidth, update_keys, return_ann_object, custom_loadings, feat_scaling, lsi_skip_first, show_elbow_plot)
   1234         graph_loc = f"{knn_loc}/graph__{local_connectivity}__{bandwidth}"
   1235 
-> 1236         data = assay.save_normalized_data(
   1237             cell_key,
   1238             feat_key,

/usr/local/lib/python3.8/dist-packages/scarf/assay.py in save_normalized_data(self, cell_key, feat_key, batch_size, location, log_transform, renormalize_subset, update_keys)
    470                 # Creating group here to overwrite all children
    471                 self.z.create_group(location, overwrite=True)
--> 472         vals = self.normed(
    473             cell_idx,
    474             feat_idx,

/usr/local/lib/python3.8/dist-packages/scarf/assay.py in normed(self, cell_idx, feat_idx, renormalize_subset, log_transform, **kwargs)
    751         else:
    752             self.scalar = self.cells.fetch_all(self.name + "_nCounts")[cell_idx]
--> 753         val = self.normMethod(self, counts)
    754         self.normMethod = norm_method_cache
    755         return val

/usr/local/lib/python3.8/dist-packages/scarf/assay.py in norm_lib_size_log(assay, counts)
     65 
     66     """
---> 67     return np.log1p(assay.sf * counts / assay.scalar.reshape(-1, 1))
     68 
     69 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'Array'

**Comment by parashardhapola** [comment]
Hi @stela2502,

This will **not** work:
`ds._get_assay('spliced').__class__ = scarf.assay.RNAassay`

A better way to do this would be when you are loading the Zarr file like this:
```
ds = scarf.DataStore(
    'scarf_datasets/data/data.zarr',
    nthreads=4,
    min_features_per_cell=100,
    assay_types={'spliced': 'RNA'}
)
```
This will change the underlying class of assay `spliced` to `RNAassay` type.

Please let me know if this does not work for you.
