### ISSUE TITLE
ds.to_anndata() and  scarf.writers.to_h5ad() crteate two different data structures

### ISSUE THREAD

**Issue by stela2502** [parashardhapola/scarf#72]
When I use the to_anndata() function in scarf 0.20.0 I get an anndata object with all requred information ([20] in the script); If I use the to_h5ad I get only a minimal anndata object lacking all UMP/TSNE information [25]. 
In addition it would be cool dimension reduction data could be stored in an obsm table instead of an obs table mimicking the scanpy behavior. 

A detailed description of what I did is in the attached html script file. 

[concat_1_EX05.pdf](https://github.com/parashardhapola/scarf/files/9336219/concat_1_EX05.pdf)

**Comment by stela2502** [comment]
And github does not accept html - hence it is a pdf now.

**Comment by stela2502** [comment]
And one other 'issue' related to drc's and anndata: Could you precede the drc names with an uppercase X_? Like create from umap1 a key names X_umap1? This would help me a lot when importing scarf data into cellexalvrR.

**Comment by parashardhapola** [comment]
Please try version `0.21.0`. Improvements were added to `to_h5ad` function. Now you get all the 'col' and 'var' data. You will also find the UMAP coords as X_umap in the 'obsm' slot.

**Comment by stela2502** [comment]
This does work perfectly! Thank you very much! No need to modify cellexalvrR any longer.
