### ISSUE TITLE
Documentation enhancement for SubsetZarr

### ISSUE THREAD

**Issue by stela2502** [parashardhapola/scarf#74]
Recently an issue was solved where scarf.writers.SubsetZarr did not produce the expected outfiles.
Now I hit the same problem following the info on this web page: https://scarf.readthedocs.io/en/latest/api.html

I would greatly appreciate if a short example could be added to the api documentation. Like:
```
writer = scarf.writers.SubsetZarr( in_zarr = "full.zarr", out_zarr = "subset.zarr", cell_key="yourBinaryKey", overwrite_existing_file=True)
writer.dump() # to write the data to disk
```

**Comment by parashardhapola** [comment]
Hi @stela2502,

The updated downsampling vignette now has some info.
https://scarf.readthedocs.io/en/latest/vignettes/cell_subsampling_tutorial.html#exporting-downsampled-data

/PD
